FROM eclipse-temurin:17-jre-focal

CMD pwd

WORKDIR /root

COPY . .
RUN ./gradlew :backendApi:shadowJar > /dev/null
RUN mv backendApi/build/libs/backendApi-*-all.jar /root/server.jar
RUN cp backendApi/src/main/resources/banner.txt /root

ENTRYPOINT ./scripts/docker-entrypoint.sh