FROM eclipse-temurin:17-jre-focal
RUN mkdir -p /home/app
WORKDIR /home/app
COPY . .
RUN env
RUN ./gradlew :backend-api:shadowJar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/home/app/backend-api/build/libs/backend-api-all.jar"]
