FROM eclipse-temurin:17-jre-focal
RUN mkdir -p /home/app
WORKDIR /home/app
COPY . .
RUN ls -l
RUN ls -l gradle/wrapper
RUN ./gradlew :backend-api:shadowJar

EXPOSE 80
ENTRYPOINT ["java", "-jar", "/home/app/backend-api/build/libs/backend-api-all.jar"]
